import { Command } from "commander";
import chalk from "chalk";

const program = new Command();

program
  .name("linkerd-config")
  .description("Generate Linkerd service mesh configurations")
  .version("1.0.0");

// ─── init ────────────────────────────────────────────────────────────────────

program
  .command("init")
  .description("Generate Linkerd installation values.yaml with trust anchor and identity")
  .option("--cluster-domain <domain>", "Cluster domain", "cluster.local")
  .option("--proxy-cpu-request <cpu>", "Proxy CPU request", "100m")
  .option("--proxy-memory-request <mem>", "Proxy memory request", "20Mi")
  .option("--proxy-cpu-limit <cpu>", "Proxy CPU limit", "1000m")
  .option("--proxy-memory-limit <mem>", "Proxy memory limit", "250Mi")
  .option("--ha", "Enable high availability mode", false)
  .action((opts) => {
    const config = `# Linkerd Installation Values
# Generated by linkerd-config-cli v1.0.0

# Global settings
clusterDomain: ${opts.clusterDomain}

# Identity configuration (trust anchor & issuer)
identity:
  issuer:
    scheme: kubernetes.io/tls
    # Mount trust anchor cert from a secret
    tls:
      crtPEM: |
        # Replace with your trust anchor certificate (PEM)
      keyPEM: |
        # Replace with your trust anchor key (PEM)
  trustAnchorsPEM: |
    # Replace with your trust anchor certificate (PEM)
  trustDomain: ${opts.clusterDomain}

# Proxy configuration
proxy:
  resources:
    cpu:
      request: "${opts.proxyCpuRequest}"
      limit: "${opts.proxyCpuLimit}"
    memory:
      request: "${opts.proxyMemoryRequest}"
      limit: "${opts.proxyMemoryLimit}"
  logLevel: warn,linkerd=info
  logFormat: plain

# Control plane configuration
controllerReplicas: ${opts.ha ? 3 : 1}
enablePodAntiAffinity: ${opts.ha}

# Prometheus / telemetry (disable if using Viz extension separately)
prometheusUrl: ""

# CNI plugin (set true if not using init containers)
cniEnabled: false

# Tracing (optional)
tracing:
  enabled: false
`;

    console.log(chalk.green("# Linkerd values.yaml\n"));
    console.log(config);
    console.log(
      chalk.yellow(
        "# Apply with: linkerd install --values values.yaml | kubectl apply -f -"
      )
    );
  });

// ─── inject ──────────────────────────────────────────────────────────────────

program
  .command("inject <file>")
  .description("Generate annotation for automatic proxy injection")
  .option("--namespace <ns>", "Target namespace", "default")
  .option("--ignore-ports <ports>", "Comma-separated ports to skip proxy for", "")
  .option("--opaque-ports <ports>", "Comma-separated ports to treat as opaque", "443")
  .action((file, opts) => {
    const ignoreSection = opts.ignorePorts
      ? `\n    config.linkerd.io/skip-inbound-ports: "${opts.ignorePorts}"\n    config.linkerd.io/skip-outbound-ports: "${opts.ignorePorts}"`
      : "";

    const annotation = `# Proxy injection patch for: ${file}
# Namespace: ${opts.namespace}
#
# Option A — annotate namespace (all pods auto-injected):
kubectl annotate namespace ${opts.namespace} linkerd.io/inject=enabled

# Option B — patch specific Deployment/Pod:
kubectl patch deployment <your-deployment> -n ${opts.namespace} --type=json -p='[
  {
    "op": "add",
    "path": "/spec/template/metadata/annotations",
    "value": {
      "linkerd.io/inject": "enabled",
      "config.linkerd.io/opaque-ports": "${opts.opaquePorts}"${ignoreSection ? "," : ""}${ignoreSection}
    }
  }
]'

# Option C — inline annotations in your manifest (add to pod template metadata):
# annotations:
#   linkerd.io/inject: "enabled"
#   config.linkerd.io/opaque-ports: "${opts.opaquePorts}"${ignoreSection ? `\n#   config.linkerd.io/skip-inbound-ports: "${opts.ignorePorts}"\n#   config.linkerd.io/skip-outbound-ports: "${opts.ignorePorts}"` : ""}
#
# Then apply the original manifest:
# linkerd inject ${file} | kubectl apply -f -
`;

    console.log(chalk.green("# Linkerd proxy injection\n"));
    console.log(annotation);
  });

// ─── profile ──────────────────────────────────────────────────────────────────

program
  .command("profile <svc>")
  .description("Generate ServiceProfile with routes, retries, and timeouts")
  .option("--namespace <ns>", "Namespace", "default")
  .option("--timeout <ms>", "Default route timeout in ms", "10000")
  .option("--retries", "Enable retries on routes", false)
  .action((svc, opts) => {
    const retriesSection = opts.retries
      ? `
      isRetryable: true`
      : "";

    const profile = `apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: ${svc}.${opts.namespace}.svc.cluster.local
  namespace: ${opts.namespace}
spec:
  routes:
    - name: GET /api/v1/health
      condition:
        method: GET
        pathRegex: /api/v1/health
      timeout: ${opts.timeout}ms${retriesSection}

    - name: GET /api/v1/items
      condition:
        method: GET
        pathRegex: /api/v1/items(/.*)?
      timeout: ${opts.timeout}ms${retriesSection}

    - name: POST /api/v1/items
      condition:
        method: POST
        pathRegex: /api/v1/items
      timeout: ${opts.timeout}ms
      # POST mutations are not retried by default

    - name: PUT /api/v1/items/{id}
      condition:
        method: PUT
        pathRegex: /api/v1/items/[^/]+
      timeout: ${opts.timeout}ms

    - name: DELETE /api/v1/items/{id}
      condition:
        method: DELETE
        pathRegex: /api/v1/items/[^/]+
      timeout: ${opts.timeout}ms
`;

    console.log(chalk.green(`# ServiceProfile for: ${svc}\n`));
    console.log(profile);
    console.log(
      chalk.yellow(`# Apply with: kubectl apply -f - <<EOF\n${profile}EOF`)
    );
  });

// ─── policy ──────────────────────────────────────────────────────────────────

program
  .command("policy <type>")
  .description(
    "Generate authorization policy (server | serverauth | meshtls)"
  )
  .option("--namespace <ns>", "Namespace", "default")
  .option("--name <name>", "Resource name", "my-policy")
  .option("--port <port>", "Target port", "8080")
  .option("--service-account <sa>", "Allowed service account", "default")
  .option("--client-namespace <ns>", "Client namespace for ServerAuthorization", "default")
  .action((type, opts) => {
    const t = type.toLowerCase();

    let manifest = "";

    if (t === "server") {
      manifest = `apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: ${opts.name}
  namespace: ${opts.namespace}
spec:
  podSelector:
    matchLabels:
      app: ${opts.name}
  port: ${opts.port}
  proxyProtocol: HTTP/2
`;
    } else if (t === "serverauth") {
      manifest = `apiVersion: policy.linkerd.io/v1beta3
kind: ServerAuthorization
metadata:
  name: ${opts.name}
  namespace: ${opts.namespace}
spec:
  server:
    name: ${opts.name}
  client:
    meshTLS:
      serviceAccounts:
        - name: ${opts.serviceAccount}
          namespace: ${opts.clientNamespace}
`;
    } else if (t === "meshtls") {
      manifest = `apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: ${opts.name}
  namespace: ${opts.namespace}
spec:
  identities:
    - "${opts.serviceAccount}.${opts.clientNamespace}.serviceaccount.identity.linkerd.cluster.local"
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: ${opts.name}-authz
  namespace: ${opts.namespace}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: ${opts.name}
  requiredAuthenticationRefs:
    - name: ${opts.name}
      kind: MeshTLSAuthentication
      group: policy.linkerd.io
`;
    } else {
      console.error(
        chalk.red(
          `Unknown policy type: ${type}. Use: server | serverauth | meshtls`
        )
      );
      process.exit(1);
    }

    console.log(chalk.green(`# Linkerd Policy — ${type}\n`));
    console.log(manifest);
    console.log(chalk.yellow("# Apply with: kubectl apply -f <file>"));
  });

// ─── multicluster ─────────────────────────────────────────────────────────────

program
  .command("multicluster")
  .description("Generate multi-cluster link and mirror service config")
  .option("--cluster-name <name>", "Remote cluster name", "remote")
  .option("--gateway-ip <ip>", "Remote gateway IP", "1.2.3.4")
  .option("--gateway-port <port>", "Remote gateway port", "4143")
  .option("--service <svc>", "Service to mirror", "my-service")
  .option("--namespace <ns>", "Service namespace", "default")
  .action((opts) => {
    const config = `# ─── Step 1: Install multicluster extension on both clusters ───
# linkerd multicluster install | kubectl apply -f -

# ─── Step 2: Link clusters ──────────────────────────────────────
# Run on the SOURCE cluster, pointing to the REMOTE cluster's kubeconfig:
# linkerd multicluster link --cluster-name ${opts.clusterName} \\
#   --kubeconfig /path/to/remote-kubeconfig | kubectl apply -f -

# ─── Step 3: Link resource (generated) ──────────────────────────
apiVersion: multicluster.linkerd.io/v1alpha1
kind: Link
metadata:
  name: ${opts.clusterName}
  namespace: linkerd-multicluster
spec:
  targetClusterName: ${opts.clusterName}
  targetClusterDomain: cluster.local
  gatewayAddress: ${opts.gatewayIp}
  gatewayPort: ${opts.gatewayPort}
  gatewayIdentity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
  probeSpec:
    path: /ready
    port: 4191
    period: 60s

---
# ─── Step 4: Export service from remote cluster ─────────────────
# On the REMOTE cluster, annotate the service:
apiVersion: v1
kind: Service
metadata:
  name: ${opts.service}
  namespace: ${opts.namespace}
  annotations:
    mirror.linkerd.io/exported: "true"
spec:
  selector:
    app: ${opts.service}
  ports:
    - port: 80
      targetPort: 8080

---
# ─── Step 5: Mirrored service (auto-created on source cluster) ──
# Linkerd will create:
#   ${opts.service}-${opts.clusterName}.${opts.namespace}.svc.cluster.local
# No manual action needed — just verify with:
# kubectl get svc -n ${opts.namespace} | grep ${opts.clusterName}
`;

    console.log(chalk.green("# Linkerd Multi-cluster Configuration\n"));
    console.log(config);
  });

// ─── viz ──────────────────────────────────────────────────────────────────────

program
  .command("viz")
  .description("Generate Linkerd Viz extension dashboard config")
  .option("--namespace <ns>", "Viz namespace", "linkerd-viz")
  .option("--replicas <n>", "Number of replicas for HA", "1")
  .option("--retention <h>", "Prometheus data retention in hours", "6h")
  .option("--external-prometheus <url>", "External Prometheus URL (skip bundled)", "")
  .option("--ingress <class>", "Ingress class for dashboard exposure", "")
  .option("--host <host>", "Dashboard hostname for ingress", "viz.example.com")
  .action((opts) => {
    const prometheusSection = opts.externalPrometheus
      ? `prometheusUrl: "${opts.externalPrometheus}"
prometheus:
  enabled: false`
      : `prometheus:
  enabled: true
  retention: ${opts.retention}
  resources:
    requests:
      cpu: 300m
      memory: 300Mi
    limits:
      cpu: "1"
      memory: 2048Mi`;

    const ingressSection =
      opts.ingress
        ? `
---
# Dashboard Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkerd-viz
  namespace: ${opts.namespace}
  annotations:
    kubernetes.io/ingress.class: "${opts.ingress}"
    nginx.ingress.kubernetes.io/upstream-vhost: \$service_name.\$namespace.svc.cluster.local:8084
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Origin "";
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  rules:
    - host: ${opts.host}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8084`
        : "";

    const config = `# Linkerd Viz Extension Values
# Install with: linkerd viz install --values viz-values.yaml | kubectl apply -f -

namespace: ${opts.namespace}

dashboard:
  replicas: ${opts.replicas}
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 250m
      memory: 250Mi

tap:
  replicas: ${opts.replicas}
  resources:
    requests:
      cpu: 100m
      memory: 20Mi
    limits:
      cpu: 250m
      memory: 250Mi

tapInjector:
  replicas: ${opts.replicas}

${prometheusSection}

# Grafana (optional — link to external)
# grafana:
#   externalUrl: "http://grafana.monitoring.svc.cluster.local:3000"
${ingressSection}`;

    console.log(chalk.green("# Linkerd Viz Configuration\n"));
    console.log(config);
    console.log(
      chalk.yellow(
        "\n# Verify dashboard: linkerd viz dashboard --address 0.0.0.0:50750"
      )
    );
  });

// ─── run ──────────────────────────────────────────────────────────────────────

program.parse(process.argv);
