import { Command } from "commander";
import chalk from "chalk";
import { readFileSync } from "fs";
import { existsSync } from "fs";

const program = new Command();

program
  .name("linkerd-config")
  .description("Generate and manage Linkerd service mesh configurations")
  .version("1.0.0");

// ─── init <type> ─────────────────────────────────────────────────────────────

program
  .command("init <type>")
  .description("Generate Linkerd install config: default | ha | multi-cluster")
  .option("--cluster-domain <domain>", "Cluster domain", "cluster.local")
  .option("--proxy-cpu-request <cpu>", "Proxy CPU request", "100m")
  .option("--proxy-memory-request <mem>", "Proxy memory request", "20Mi")
  .option("--proxy-cpu-limit <cpu>", "Proxy CPU limit", "1000m")
  .option("--proxy-memory-limit <mem>", "Proxy memory limit", "250Mi")
  .option("--opaque-ports <ports>", "Opaque ports (comma-separated)", "25,587,3306,4444,5432,6379,9300,11211")
  .option("--skip-inbound-ports <ports>", "Skip inbound ports", "")
  .option("--skip-outbound-ports <ports>", "Skip outbound ports", "")
  .action((type, opts) => {
    const t = type.toLowerCase();
    if (!["default", "ha", "multi-cluster"].includes(t)) {
      console.error(chalk.red(`Unknown type: ${type}. Use: default | ha | multi-cluster`));
      process.exit(1);
    }

    const isHA = t === "ha";
    const isMulti = t === "multi-cluster";
    const replicas = isHA || isMulti ? 3 : 1;

    const skipInbound = opts.skipInboundPorts ? `\n  skipInboundPorts: "${opts.skipInboundPorts}"` : "";
    const skipOutbound = opts.skipOutboundPorts ? `\n  skipOutboundPorts: "${opts.skipOutboundPorts}"` : "";

    const multiclusterSection = isMulti ? `
# Multi-cluster gateway
gateway:
  enabled: true
  replicas: ${replicas}
  serviceAnnotations: {}

# Link configuration (run: linkerd multicluster install | kubectl apply -f -)
multicluster:
  enabled: true
` : "";

    const manifest = `# Linkerd Install Config — ${t.toUpperCase()}
# Generated by linkerd-config-cli v1.0.0
# Apply: linkerd install --values values.yaml | kubectl apply -f -

clusterDomain: ${opts.clusterDomain}

# Identity & trust anchor rotation
identity:
  issuer:
    scheme: kubernetes.io/tls
    tls:
      crtPEM: |
        # Replace with issuer certificate (PEM)
      keyPEM: |
        # Replace with issuer key (PEM)
  trustAnchorsPEM: |
    # Replace with trust anchor certificate (PEM)
    # Rotate with: linkerd upgrade --identity-trust-anchors-file new-anchor.pem
  trustDomain: ${opts.clusterDomain}

# Proxy resources & configuration
proxy:
  resources:
    cpu:
      request: "${opts.proxyCpuRequest}"
      limit: "${opts.proxyCpuLimit}"
    memory:
      request: "${opts.proxyMemoryRequest}"
      limit: "${opts.proxyMemoryLimit}"
  logLevel: warn,linkerd=info
  logFormat: plain
  opaquePorts: "${opts.opaquePorts}"${skipInbound}${skipOutbound}
  # Circuit breaking via timeout + retry budgets configured in ServiceProfile
  # Tap policy: enable/disable request inspection
  enableExternalProfiles: true

# Control plane HA
controllerReplicas: ${replicas}
enablePodAntiAffinity: ${isHA || isMulti}
${isHA || isMulti ? `
# HA: webhook replicas
webhookFailurePolicy: Fail
proxyInjector:
  replicas: ${replicas}
profileValidator:
  replicas: ${replicas}
policyValidator:
  replicas: ${replicas}
` : ""}
# CNI (set true to avoid init containers)
cniEnabled: false

# Tracing
tracing:
  enabled: false
${multiclusterSection}`;

    console.log(chalk.green(`# Linkerd ${t} config\n`));
    console.log(manifest);
    console.log(chalk.yellow("# Apply: linkerd install --values values.yaml | kubectl apply -f -"));
  });

// ─── add-service-profile <name> ──────────────────────────────────────────────

program
  .command("add-service-profile <name>")
  .description("Generate ServiceProfile with routes, retries, and timeouts")
  .option("--namespace <ns>", "Namespace", "default")
  .option("--timeout <ms>", "Default route timeout", "10000ms")
  .option("--retries", "Enable retries on GET routes", false)
  .option("--retry-budget-ratio <ratio>", "Retry budget ratio", "0.2")
  .option("--retry-budget-min <rps>", "Retry budget minimum RPS", "10")
  .action((name, opts) => {
    const retryBudget = `
  retryBudget:
    retryRatio: ${opts.retryBudgetRatio}
    minRetriesPerSecond: ${parseInt(opts.retryBudgetMin)}
    ttl: 10s`;

    const isRetryable = opts.retries ? "\n      isRetryable: true" : "";

    const manifest = `apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: ${name}.${opts.namespace}.svc.cluster.local
  namespace: ${opts.namespace}
spec:${retryBudget}
  routes:
    - name: GET /healthz
      condition:
        method: GET
        pathRegex: /healthz(/.*)?
      timeout: 5000ms${opts.retries ? "\n      isRetryable: true" : ""}

    - name: GET /api/v1/.*
      condition:
        method: GET
        pathRegex: /api/v1/.*
      timeout: ${opts.timeout}${isRetryable}

    - name: POST /api/v1/.*
      condition:
        method: POST
        pathRegex: /api/v1/.*
      timeout: ${opts.timeout}
      # POST mutations are not retried by default

    - name: PUT /api/v1/.*
      condition:
        method: PUT
        pathRegex: /api/v1/.*
      timeout: ${opts.timeout}

    - name: DELETE /api/v1/.*
      condition:
        method: DELETE
        pathRegex: /api/v1/.*
      timeout: ${opts.timeout}
`;

    console.log(chalk.green(`# ServiceProfile: ${name}\n`));
    console.log(manifest);
    console.log(chalk.yellow(`# Apply: kubectl apply -f ${name}-serviceprofile.yaml`));
  });

// ─── add-traffic-split <name> ────────────────────────────────────────────────

program
  .command("add-traffic-split <name>")
  .description("Generate TrafficSplit for canary deployments")
  .option("--namespace <ns>", "Namespace", "default")
  .option("--stable-weight <w>", "Stable backend weight", "900")
  .option("--canary-weight <w>", "Canary backend weight", "100")
  .option("--stable-service <svc>", "Stable service name", "")
  .option("--canary-service <svc>", "Canary service name", "")
  .action((name, opts) => {
    const stableSvc = opts.stableService || `${name}-stable`;
    const canarySvc = opts.canaryService || `${name}-canary`;

    const manifest = `# TrafficSplit — canary deployment for: ${name}
# SMI TrafficSplit v1alpha2
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: ${name}
  namespace: ${opts.namespace}
spec:
  # Root service — clients call this
  service: ${name}
  backends:
    - service: ${stableSvc}
      weight: ${opts.stableWeight}m
    - service: ${canarySvc}
      weight: ${opts.canaryWeight}m

---
# Stable service (points to current production pods)
apiVersion: v1
kind: Service
metadata:
  name: ${stableSvc}
  namespace: ${opts.namespace}
spec:
  selector:
    app: ${name}
    version: stable
  ports:
    - port: 80
      targetPort: 8080

---
# Canary service (points to new version pods)
apiVersion: v1
kind: Service
metadata:
  name: ${canarySvc}
  namespace: ${opts.namespace}
spec:
  selector:
    app: ${name}
    version: canary
  ports:
    - port: 80
      targetPort: 8080

# Rollout strategy:
# 1. Start: stable=900m canary=100m  (~10% traffic to canary)
# 2. Monitor: linkerd viz stat deploy -n ${opts.namespace}
# 3. Progress: increase canary weight, decrease stable weight
# 4. Complete: set canary=1000m stable=0m, then remove TrafficSplit
# 5. Rollback: set canary=0m stable=1000m immediately
`;

    console.log(chalk.green(`# TrafficSplit: ${name}\n`));
    console.log(manifest);
    console.log(chalk.yellow(`# Apply: kubectl apply -f ${name}-trafficsplit.yaml`));
  });

// ─── add-auth-policy <name> ──────────────────────────────────────────────────

program
  .command("add-auth-policy <name>")
  .description("Generate ServerAuthorization policy for mTLS")
  .option("--namespace <ns>", "Namespace", "default")
  .option("--port <port>", "Server port", "8080")
  .option("--protocol <proto>", "Proxy protocol (HTTP/1, HTTP/2, gRPC, opaque, TLS)", "HTTP/2")
  .option("--service-account <sa>", "Allowed service account", "default")
  .option("--client-namespace <ns>", "Client service account namespace", "default")
  .option("--all-authenticated", "Allow all authenticated mesh clients", false)
  .action((name, opts) => {
    const clientSpec = opts.allAuthenticated
      ? `    meshTLS:
      unauthenticatedTLS: false
      # Allow any authenticated mesh identity`
      : `    meshTLS:
      serviceAccounts:
        - name: ${opts.serviceAccount}
          namespace: ${opts.clientNamespace}`;

    const manifest = `# Server + ServerAuthorization for mTLS policy: ${name}
apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: ${name}
  namespace: ${opts.namespace}
  labels:
    app: ${name}
spec:
  podSelector:
    matchLabels:
      app: ${name}
  port: ${opts.port}
  proxyProtocol: ${opts.protocol}

---
apiVersion: policy.linkerd.io/v1beta3
kind: ServerAuthorization
metadata:
  name: ${name}-authz
  namespace: ${opts.namespace}
spec:
  server:
    name: ${name}
  client:
${clientSpec}

---
# MeshTLS Authentication resource (policy.linkerd.io/v1alpha1)
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: ${name}-meshtls
  namespace: ${opts.namespace}
spec:
  identities:
    - "${opts.serviceAccount}.${opts.clientNamespace}.serviceaccount.identity.linkerd.cluster.local"

---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: ${name}-policy
  namespace: ${opts.namespace}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: ${name}
  requiredAuthenticationRefs:
    - name: ${name}-meshtls
      kind: MeshTLSAuthentication
      group: policy.linkerd.io

# Verify mTLS: linkerd viz edges deploy -n ${opts.namespace}
# Tap traffic: linkerd viz tap deploy/${name} -n ${opts.namespace}
`;

    console.log(chalk.green(`# Auth Policy (mTLS): ${name}\n`));
    console.log(manifest);
    console.log(chalk.yellow(`# Apply: kubectl apply -f ${name}-auth-policy.yaml`));
  });

// ─── add-inject <namespace> ──────────────────────────────────────────────────

program
  .command("add-inject <namespace>")
  .description("Generate namespace annotation for auto-injection")
  .option("--opaque-ports <ports>", "Opaque ports", "25,587,3306,4444,5432,6379,9300,11211")
  .option("--skip-inbound-ports <ports>", "Skip inbound ports (comma-separated)", "")
  .option("--skip-outbound-ports <ports>", "Skip outbound ports (comma-separated)", "")
  .option("--proxy-cpu-request <cpu>", "Proxy CPU request override", "")
  .option("--proxy-memory-request <mem>", "Proxy memory request override", "")
  .option("--disable", "Disable injection (annotate with disabled)", false)
  .action((namespace, opts) => {
    const injectValue = opts.disable ? "disabled" : "enabled";
    const extraAnnotations: string[] = [];

    if (opts.opaquePorts) extraAnnotations.push(`  config.linkerd.io/opaque-ports: "${opts.opaquePorts}"`);
    if (opts.skipInboundPorts) extraAnnotations.push(`  config.linkerd.io/skip-inbound-ports: "${opts.skipInboundPorts}"`);
    if (opts.skipOutboundPorts) extraAnnotations.push(`  config.linkerd.io/skip-outbound-ports: "${opts.skipOutboundPorts}"`);
    if (opts.proxyCpuRequest) extraAnnotations.push(`  config.linkerd.io/proxy-cpu-request: "${opts.proxyCpuRequest}"`);
    if (opts.proxyMemoryRequest) extraAnnotations.push(`  config.linkerd.io/proxy-memory-request: "${opts.proxyMemoryRequest}"`);

    const annotationsBlock = extraAnnotations.length > 0
      ? "\n" + extraAnnotations.join("\n")
      : "";

    const manifest = `apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
  annotations:
    linkerd.io/inject: "${injectValue}"${annotationsBlock}
  labels:
    linkerd.io/inject: "${injectValue}"

# To apply annotation to existing namespace:
# kubectl annotate namespace ${namespace} linkerd.io/inject=${injectValue} --overwrite

# Verify injection after deploying pods:
# linkerd check --namespace ${namespace}
# kubectl get pods -n ${namespace} -o jsonpath='{range .items[*]}{.metadata.name}{" containers:"}{range .spec.containers[*]}{.name}{" "}{end}{"\\n"}{end}'
`;

    console.log(chalk.green(`# Namespace injection: ${namespace} (${injectValue})\n`));
    console.log(manifest);
    console.log(chalk.yellow(`# Apply: kubectl apply -f ${namespace}-inject.yaml`));
  });

// ─── add-multicluster <cluster> ──────────────────────────────────────────────

program
  .command("add-multicluster <cluster>")
  .description("Generate multi-cluster link and mirror config")
  .option("--gateway-ip <ip>", "Remote gateway IP", "1.2.3.4")
  .option("--gateway-port <port>", "Remote gateway port", "4143")
  .option("--probe-port <port>", "Probe port", "4191")
  .option("--namespace <ns>", "Multicluster namespace", "linkerd-multicluster")
  .option("--service <svc>", "Service to export/mirror", "my-service")
  .option("--service-namespace <ns>", "Service namespace", "default")
  .action((cluster, opts) => {
    const manifest = `# Linkerd Multi-cluster: link to ${cluster}
# Prerequisites: linkerd multicluster install | kubectl apply -f -

# ─── Step 1: Link resource ───────────────────────────────────────
apiVersion: multicluster.linkerd.io/v1alpha1
kind: Link
metadata:
  name: ${cluster}
  namespace: ${opts.namespace}
spec:
  targetClusterName: ${cluster}
  targetClusterDomain: cluster.local
  gatewayAddress: ${opts.gatewayIp}
  gatewayPort: ${opts.gatewayPort}
  gatewayIdentity: linkerd-gateway.${opts.namespace}.serviceaccount.identity.linkerd.cluster.local
  probeSpec:
    path: /ready
    port: ${opts.probePort}
    period: 60s

---
# ─── Step 2: Export service from remote cluster ──────────────────
# (Apply this on the REMOTE cluster)
apiVersion: v1
kind: Service
metadata:
  name: ${opts.service}
  namespace: ${opts.serviceNamespace}
  annotations:
    mirror.linkerd.io/exported: "true"
spec:
  selector:
    app: ${opts.service}
  ports:
    - port: 80
      targetPort: 8080

# ─── Step 3: Use mirrored service on source cluster ──────────────
# After linking, Linkerd auto-creates:
#   ${opts.service}-${cluster}.${opts.serviceNamespace}.svc.cluster.local
#
# Reference it in ServiceProfile for cross-cluster retries:
#   name: ${opts.service}-${cluster}.${opts.serviceNamespace}.svc.cluster.local
#
# Verify: linkerd multicluster check
# Status: linkerd multicluster gateways
# kubectl get svc -n ${opts.serviceNamespace} | grep ${cluster}
`;

    console.log(chalk.green(`# Multi-cluster link: ${cluster}\n`));
    console.log(manifest);
    console.log(chalk.yellow(`# Apply on source cluster: kubectl apply -f ${cluster}-multicluster.yaml`));
  });

// ─── add-viz ─────────────────────────────────────────────────────────────────

program
  .command("add-viz")
  .description("Generate Linkerd Viz extension config with Grafana dashboards")
  .option("--namespace <ns>", "Viz namespace", "linkerd-viz")
  .option("--replicas <n>", "Replicas for HA", "1")
  .option("--retention <dur>", "Prometheus retention", "6h")
  .option("--external-prometheus <url>", "External Prometheus URL", "")
  .option("--grafana-url <url>", "External Grafana URL", "")
  .option("--ingress-class <class>", "Ingress class for dashboard", "")
  .option("--host <host>", "Dashboard hostname", "viz.example.com")
  .action((opts) => {
    const prometheusSection = opts.externalPrometheus
      ? `prometheusUrl: "${opts.externalPrometheus}"
prometheus:
  enabled: false`
      : `prometheus:
  enabled: true
  retention: ${opts.retention}
  resources:
    requests:
      cpu: 300m
      memory: 300Mi
    limits:
      cpu: "1"
      memory: 2048Mi`;

    const grafanaSection = opts.grafanaUrl
      ? `grafana:
  externalUrl: "${opts.grafanaUrl}"
  # Dashboards: Top Line Metrics, Route Details, Namespace Overview`
      : `# grafana:
#   externalUrl: "http://grafana.monitoring.svc.cluster.local:3000"
#   Dashboards available at: /grafana (auto-configured via Linkerd datasource)`;

    const ingressSection = opts.ingressClass ? `
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkerd-viz
  namespace: ${opts.namespace}
  annotations:
    kubernetes.io/ingress.class: "${opts.ingressClass}"
    nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local:8084
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Origin "";
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  rules:
    - host: ${opts.host}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8084` : "";

    const manifest = `# Linkerd Viz Extension Values
# Install: linkerd viz install --values viz-values.yaml | kubectl apply -f -

namespace: ${opts.namespace}

dashboard:
  replicas: ${opts.replicas}
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 250m
      memory: 250Mi

tap:
  replicas: ${opts.replicas}
  resources:
    requests:
      cpu: 100m
      memory: 20Mi
    limits:
      cpu: 250m
      memory: 250Mi

tapInjector:
  replicas: ${opts.replicas}

${prometheusSection}

${grafanaSection}
${ingressSection}

# Usage:
# linkerd viz dashboard              — open dashboard in browser
# linkerd viz stat deploy            — golden metrics (RPS, latency, success)
# linkerd viz tap deploy/my-app      — live request inspection
# linkerd viz routes deploy/my-app   — per-route metrics
# linkerd viz edges deploy           — mTLS edges
`;

    console.log(chalk.green("# Linkerd Viz Extension Config\n"));
    console.log(manifest);
    console.log(chalk.yellow("# Verify: linkerd viz check"));
  });

// ─── validate [file] ─────────────────────────────────────────────────────────

program
  .command("validate [file]")
  .description("Validate Linkerd YAML manifests")
  .option("--strict", "Fail on warnings too", false)
  .action((file, opts) => {
    const LINKERD_KINDS = [
      "ServiceProfile",
      "TrafficSplit",
      "Server",
      "ServerAuthorization",
      "MeshTLSAuthentication",
      "AuthorizationPolicy",
      "Link",
    ];

    const LINKERD_API_GROUPS = [
      "linkerd.io",
      "policy.linkerd.io",
      "split.smi-spec.io",
      "multicluster.linkerd.io",
    ];

    if (!file) {
      console.log(chalk.yellow("# No file specified — showing validation rules\n"));
      console.log(`Linkerd manifest validation checks:

${chalk.cyan("Required fields:")}
  - apiVersion  (must match a Linkerd API group)
  - kind        (must be a known Linkerd resource type)
  - metadata.name
  - metadata.namespace
  - spec

${chalk.cyan("Supported API groups:")}
${LINKERD_API_GROUPS.map(g => `  - ${g}`).join("\n")}

${chalk.cyan("Supported resource kinds:")}
${LINKERD_KINDS.map(k => `  - ${k}`).join("\n")}

${chalk.cyan("ServiceProfile checks:")}
  - spec.routes must be an array
  - Each route must have: name, condition.method, condition.pathRegex
  - timeout format: <number>ms (e.g. 5000ms)
  - retryBudget: retryRatio 0-1, minRetriesPerSecond > 0, ttl format

${chalk.cyan("TrafficSplit checks:")}
  - spec.service must be set
  - spec.backends must have >= 2 entries
  - weights use millicores (e.g. 900m) — sum should equal 1000m

${chalk.cyan("Server checks:")}
  - spec.podSelector or spec.externalWorkloadSelector required
  - spec.port required
  - proxyProtocol: HTTP/1 | HTTP/2 | gRPC | opaque | TLS

${chalk.cyan("ServerAuthorization checks:")}
  - spec.server.name required
  - spec.client must have at least one of: meshTLS, unauthenticated

${chalk.cyan("Common issues:")}
  - ServiceProfile name must match: <svc>.<namespace>.svc.<clusterDomain>
  - TrafficSplit in same namespace as root service
  - mTLS identity format: <sa>.<ns>.serviceaccount.identity.linkerd.<domain>

${chalk.cyan("CLI validation:")}
  linkerd check                    — control plane health
  linkerd check --proxy            — data plane health
  linkerd viz check                — viz extension health
  kubectl apply --dry-run=server   — server-side dry run`);
      return;
    }

    if (!existsSync(file)) {
      console.error(chalk.red(`File not found: ${file}`));
      process.exit(1);
    }

    const content = readFileSync(file, "utf-8");
    const errors: string[] = [];
    const warnings: string[] = [];
    const infos: string[] = [];

    // Split multi-doc YAML
    const docs = content.split(/^---\s*$/m).filter(d => d.trim().length > 0);
    let docIndex = 0;

    for (const doc of docs) {
      docIndex++;
      const prefix = docs.length > 1 ? `[doc ${docIndex}] ` : "";

      // Basic field checks via regex (no full YAML parser dep)
      const hasApiVersion = /^\s*apiVersion\s*:/m.test(doc);
      const hasKind = /^\s*kind\s*:/m.test(doc);
      const hasName = /^\s*name\s*:/m.test(doc);
      const hasNamespace = /^\s*namespace\s*:/m.test(doc);
      const hasSpec = /^\s*spec\s*:/m.test(doc);

      const apiVersionMatch = doc.match(/^\s*apiVersion\s*:\s*(.+)$/m);
      const kindMatch = doc.match(/^\s*kind\s*:\s*(.+)$/m);
      const apiVersion = apiVersionMatch ? apiVersionMatch[1].trim() : "";
      const kind = kindMatch ? kindMatch[1].trim() : "";

      if (!hasApiVersion) errors.push(`${prefix}Missing: apiVersion`);
      if (!hasKind) errors.push(`${prefix}Missing: kind`);
      if (!hasName) errors.push(`${prefix}Missing: metadata.name`);
      if (!hasNamespace) warnings.push(`${prefix}Missing: metadata.namespace (recommended)`);
      if (!hasSpec && kind !== "Namespace") errors.push(`${prefix}Missing: spec`);

      if (apiVersion && !LINKERD_API_GROUPS.some(g => apiVersion.startsWith(g))) {
        if (apiVersion !== "v1" && !apiVersion.startsWith("apps/") && !apiVersion.startsWith("networking.k8s.io")) {
          warnings.push(`${prefix}apiVersion "${apiVersion}" is not a known Linkerd API group`);
        }
      }

      if (kind && LINKERD_KINDS.includes(kind)) {
        infos.push(`${prefix}Found Linkerd resource: ${kind}`);

        if (kind === "ServiceProfile") {
          if (!/spec:\s*\n(\s+\w.*\n)*\s+routes:/m.test(doc)) {
            warnings.push(`${prefix}ServiceProfile: spec.routes not found`);
          }
          // Check name format
          const nameMatch = doc.match(/^\s*name\s*:\s*(.+)$/m);
          if (nameMatch && !nameMatch[1].includes(".svc.")) {
            warnings.push(`${prefix}ServiceProfile name should match: <svc>.<ns>.svc.cluster.local`);
          }
        }

        if (kind === "TrafficSplit") {
          if (!/backends:/m.test(doc)) {
            errors.push(`${prefix}TrafficSplit: spec.backends required`);
          }
          if (!/service:/m.test(doc)) {
            errors.push(`${prefix}TrafficSplit: spec.service (root service) required`);
          }
        }

        if (kind === "Server") {
          if (!/port:/m.test(doc)) {
            errors.push(`${prefix}Server: spec.port required`);
          }
          if (!/podSelector:|externalWorkloadSelector:/m.test(doc)) {
            errors.push(`${prefix}Server: spec.podSelector or spec.externalWorkloadSelector required`);
          }
        }

        if (kind === "ServerAuthorization") {
          if (!/meshTLS:|unauthenticated:/m.test(doc)) {
            errors.push(`${prefix}ServerAuthorization: spec.client must specify meshTLS or unauthenticated`);
          }
        }
      }
    }

    console.log(chalk.green(`# Validating: ${file} (${docs.length} document${docs.length !== 1 ? "s" : ""})\n`));

    if (infos.length > 0) {
      console.log(chalk.cyan("Resources found:"));
      infos.forEach(i => console.log(chalk.cyan(`  ✓ ${i}`)));
      console.log();
    }

    if (errors.length === 0 && warnings.length === 0) {
      console.log(chalk.green("✓ No issues found"));
    }

    if (warnings.length > 0) {
      console.log(chalk.yellow("Warnings:"));
      warnings.forEach(w => console.log(chalk.yellow(`  ⚠ ${w}`)));
      console.log();
    }

    if (errors.length > 0) {
      console.log(chalk.red("Errors:"));
      errors.forEach(e => console.log(chalk.red(`  ✗ ${e}`)));
      console.log();
    }

    const hasIssues = errors.length > 0 || (opts.strict && warnings.length > 0);
    if (hasIssues) {
      console.log(chalk.red(`Validation failed: ${errors.length} error(s), ${warnings.length} warning(s)`));
      console.log(chalk.yellow("\n# Also run: kubectl apply --dry-run=server -f " + file));
      process.exit(1);
    } else {
      console.log(chalk.green(`Validation passed (${errors.length} errors, ${warnings.length} warnings)`));
      console.log(chalk.yellow("\n# Also run: linkerd check && kubectl apply --dry-run=server -f " + file));
    }
  });

// ─── run ─────────────────────────────────────────────────────────────────────

program.parse(process.argv);
